ci-mysql:
  image: mysql:5.7
  ports: 
    - "13306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
local-mysql:
  image: mysql:5.7
  ports: 
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
  restart: always
local-pg:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=postgres
