// Code generated by "stringer -type PlanType types/plan_type.go"; DO NOT EDIT

package types

import "fmt"

const _PlanType_name = "SINGLETONREPEATABLE"

var _PlanType_index = [...]uint8{0, 9, 19}

func (i PlanType) String() string {
	if i < 0 || i >= PlanType(len(_PlanType_index)-1) {
		return fmt.Sprintf("PlanType(%d)", i)
	}
	return _PlanType_name[_PlanType_index[i]:_PlanType_index[i+1]]
}
